
const MarketAPI=(()=>{
'use strict';
const FIAT_CATALOG={BRL:['Real Brasileiro','🇧🇷',5.10],USD:['Dólar Americano','🇺🇸',1],EUR:['Euro','🇪🇺',.87],GBP:['Libra Esterlina','🇬🇧',.75],CHF:['Franco Suíço','🇨🇭',.81],JPY:['Iene Japonês','🇯🇵',157],CNY:['Yuan Chinês','🇨🇳',6.76],CAD:['Dólar Canadense','🇨🇦',1.40],AUD:['Dólar Australiano','🇦🇺',1.43],ARS:['Peso Argentino','🇦🇷',1490],MXN:['Peso Mexicano','🇲🇽',17.3],CLP:['Peso Chileno','🇨🇱',925],COP:['Peso Colombiano','🇨🇴',3238],PEN:['Sol Peruano','🇵🇪',3.38],PYG:['Guarani Paraguaio','🇵🇾',5972],UYU:['Peso Uruguaio','🇺🇾',40.3],BOB:['Boliviano','🇧🇴',6.91],RUB:['Rublo Russo','🇷🇺',80.4],INR:['Rupia Indiana','🇮🇳',95.4],KRW:['Won Sul-Coreano','🇰🇷',1428],SGD:['Dólar de Singapura','🇸🇬',1.28],SEK:['Coroa Sueca','🇸🇪',9.56],NOK:['Coroa Norueguesa','🇳🇴',9.54],DKK:['Coroa Dinamarquesa','🇩🇰',6.49],ZAR:['Rand Sul-Africano','🇿🇦',16.5],TRY:['Lira Turca','🇹🇷',47.5],AED:['Dirham dos Emirados','🇦🇪',3.67],SAR:['Riyal Saudita','🇸🇦',3.75],THB:['Baht Tailandês','🇹🇭',33.4],MYR:['Ringgit Malaio','🇲🇾',4.10],HKD:['Dólar de Hong Kong','🇭🇰',7.84],NZD:['Dólar Neozelandês','🇳🇿',1.70],IDR:['Rupia Indonésia','🇮🇩',18035],PHP:['Peso Filipino','🇵🇭',61],VND:['Dong Vietnamita','🇻🇳',26278],TWD:['Novo Dólar Taiwanês','🇹🇼',32.4],ILS:['Novo Shekel Israelense','🇮🇱',3.04],PLN:['Zloty Polonês','🇵🇱',3.75],CZK:['Coroa Tcheca','🇨🇿',21],HUF:['Forint Húngaro','🇭🇺',316],RON:['Leu Romeno','🇷🇴',4.56],BGN:['Lev Búlgaro','🇧🇬',1.70],ISK:['Coroa Islandesa','🇮🇸',123],EGP:['Libra Egípcia','🇪🇬',50],NGN:['Naira Nigeriana','🇳🇬',1364],KES:['Xelim Queniano','🇰🇪',129],MAD:['Dirham Marroquino','🇲🇦',9.34],QAR:['Riyal Catariano','🇶🇦',3.64],KWD:['Dinar Kuwaitiano','🇰🇼',.31],BHD:['Dinar do Bahrein','🇧🇭',.376],OMR:['Rial Omanense','🇴🇲',.385],PKR:['Rupia Paquistanesa','🇵🇰',278],BDT:['Taka de Bangladesh','🇧🇩',124],LKR:['Rupia do Sri Lanka','🇱🇰',336],UAH:['Hryvnia Ucraniana','🇺🇦',44.8]};
const REQUIRED_CRYPTO={BTC:['bitcoin','Bitcoin','₿',64000],ETH:['ethereum','Ethereum','Ξ',1870],SOL:['solana','Solana','◎',74],BNB:['binancecoin','BNB','B',593],XRP:['ripple','XRP','✕',1.08],ADA:['cardano','Cardano','₳',.19],DOGE:['dogecoin','Dogecoin','Ð',.07],TRX:['tron','TRON','T',.33],DOT:['polkadot','Polkadot','●',1.45],LINK:['chainlink','Chainlink','⬡',8.2],LTC:['litecoin','Litecoin','Ł',44.6],AVAX:['avalanche-2','Avalanche','A',6.9],XLM:['stellar','Stellar','✦',.17],XMR:['monero','Monero','ɱ',363],TON:['the-open-network','Toncoin','◇',1.65],SHIB:['shiba-inu','Shiba Inu','S',.000005],SUI:['sui','Sui','S',.68],APT:['aptos','Aptos','A',1.9],ATOM:['cosmos','Cosmos','⚛',2.1],HBAR:['hedera-hashgraph','Hedera','H',.075],ICP:['internet-computer','Internet Computer','∞',3.1],NEAR:['near','NEAR Protocol','N',1.75],ARB:['arbitrum','Arbitrum','A',.09],OP:['optimism','Optimism','O',.09],PEPE:['pepe','Pepe','P',.000003]};
const EXTRA_FIAT_CODES='AFN ALL AMD ANG AOA AWG AZN BAM BBD BDT BGN BIF BMD BND BOB BSD BTN BWP BYN BZD CDF CRC CUP CVE DJF DOP DZD ETB FJD FKP GEL GHS GIP GMD GNF GTQ GYD HNL HRK HTG IQD IRR JMD JOD KGS KHR KMF KYD KZT LAK LBP LRD LSL LYD MDL MGA MKD MMK MNT MOP MRU MUR MVR MWK MZN NAD NIO NPR PAB PGK RSD RWF SBD SCR SDG SHP SLE SLL SOS SRD SSP STN SVC SZL TJS TMT TND TOP TTD TZS UGX UZS VES VUV WST XAF XCD XOF XPF YER ZMW ZWL'.split(' ');
const ALL_FIAT_CODES=[...new Set([...Object.keys(FIAT_CATALOG),...EXTRA_FIAT_CODES])];
const currencyNames=typeof Intl.DisplayNames==='function'?new Intl.DisplayNames(['pt-BR'],{type:'currency'}):null;
function fiatMeta(code){return FIAT_CATALOG[code]?{name:FIAT_CATALOG[code][0],flag:FIAT_CATALOG[code][1]}:{name:currencyNames?.of(code)||code,flag:'💱'}}
function makeSparkline(base,change=0,points=24){const values=[],start=base/(1+change/100||1);for(let i=0;i<points;i++){const p=i/(points-1||1),wave=Math.sin(i*.85)*base*.004+Math.cos(i*.31)*base*.002;values.push(Math.max(0,start+(base-start)*p+wave))}values[values.length-1]=base;return values}
const CRYPTO_MOCK=Object.fromEntries(Object.entries(REQUIRED_CRYPTO).map(([ticker,[id,name,icon,price]],index)=>[ticker,{id,name,ticker,icon,priceUSD:price,change:((index%7)-3)*.72,change7d:((index%9)-4)*1.18,change30d:((index%11)-5)*2.15,high:price*1.025,low:price*.975,volume:Math.max(25e6,price*1.2e6),marketCap:Math.max(1e9,price*18e6),sparkline:makeSparkline(price,((index%7)-3)*.72,24),lastUpdated:new Date().toISOString()}]));
const FIAT_MOCK_BASE=Object.fromEntries(Object.entries(FIAT_CATALOG).map(([code,[name,flag,rate]])=>[code,{name,flag,rate}]));
async function fetchJSON(url,timeout=6500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
async function fetchFirst(urls){let error;for(const url of urls){try{return await fetchJSON(url)}catch(err){error=err}}throw error||new Error('Fonte indisponível')}
async function fetchFiat(base='USD'){const code=base.toLowerCase(),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);try{const latest=await fetchFirst([`https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/${code}.json`,`https://latest.currency-api.pages.dev/v1/currencies/${code}.json`]);const previous=await fetchFirst([`https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@${yesterday}/v1/currencies/${code}.json`,`https://${yesterday}.currency-api.pages.dev/v1/currencies/${code}.json`]).catch(()=>null);const currentRaw=latest[code],previousRaw=previous?.[code]||{};if(!currentRaw)throw new Error('Câmbio inválido');const rates={},changes={},sparklines={};ALL_FIAT_CODES.forEach(currency=>{const key=currency.toLowerCase(),current=Number(currentRaw[key]),before=Number(previousRaw[key]),fallback=FIAT_CATALOG[currency]?.[2];if(!(Number.isFinite(current)&&current>0)&&!fallback)return;rates[currency]=Number.isFinite(current)&&current>0?current:fallback;changes[currency]=Number.isFinite(before)&&before>0?(rates[currency]-before)/before*100:0;sparklines[currency]=makeSparkline(rates[currency],changes[currency],20)});rates[base]=1;changes[base]=0;return{rates,changes,sparklines,timestamp:new Date().toISOString(),source:'currency-api',mock:false}}catch{try{const json=await fetchJSON(`https://open.er-api.com/v6/latest/${base}`);const rates={},changes={},sparklines={};ALL_FIAT_CODES.forEach(currency=>{const rate=Number(json.rates?.[currency])||FIAT_CATALOG[currency]?.[2];if(!rate)return;rates[currency]=rate;changes[currency]=0;sparklines[currency]=makeSparkline(rate,0,20)});return{rates,changes,sparklines,timestamp:new Date().toISOString(),source:'er-api',mock:false}}catch{const rates={},changes={},sparklines={};Object.entries(FIAT_CATALOG).forEach(([currency,meta],index)=>{rates[currency]=meta[2];changes[currency]=((index%9)-4)*.08;sparklines[currency]=makeSparkline(rates[currency],changes[currency],20)});return{rates,changes,sparklines,timestamp:new Date().toISOString(),source:'offline',mock:true}}}}
async function fetchCrypto(){try{const array=await fetchJSON('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true&price_change_percentage=24h,7d,30d',8000);if(!Array.isArray(array))throw new Error('Cripto inválido');const map={};array.forEach(asset=>{const ticker=String(asset.symbol||'').toUpperCase();if(!ticker||map[ticker])return;map[ticker]={id:asset.id,name:asset.name,ticker,icon:CRYPTO_MOCK[ticker]?.icon||'●',image:asset.image||'',priceUSD:Number(asset.current_price)||0,change:Number(asset.price_change_percentage_24h)||0,change7d:Number(asset.price_change_percentage_7d_in_currency)||0,change30d:Number(asset.price_change_percentage_30d_in_currency)||0,high:Number(asset.high_24h)||Number(asset.current_price)||0,low:Number(asset.low_24h)||Number(asset.current_price)||0,volume:Number(asset.total_volume)||0,marketCap:Number(asset.market_cap)||0,ath:Number(asset.ath)||0,atl:Number(asset.atl)||0,sparkline:Array.isArray(asset.sparkline_in_7d?.price)?asset.sparkline_in_7d.price:makeSparkline(Number(asset.current_price)||1,Number(asset.price_change_percentage_24h)||0,24),lastUpdated:asset.last_updated||new Date().toISOString()}});Object.entries(CRYPTO_MOCK).forEach(([ticker,fallback])=>{if(!map[ticker])map[ticker]={...fallback}});return{cryptos:map,timestamp:new Date().toISOString(),source:'coingecko',mock:false}}catch{return{cryptos:Object.fromEntries(Object.entries(CRYPTO_MOCK).map(([ticker,item])=>[ticker,{...item,lastUpdated:new Date().toISOString()}])),timestamp:new Date().toISOString(),source:'offline',mock:true}}}
async function fetchAll(base='USD'){const[fiat,crypto]=await Promise.all([fetchFiat(base),fetchCrypto()]);const payload={key:'market_cache',fiat:fiat.rates,fiatChanges:fiat.changes,fiatSparklines:fiat.sparklines,crypto:crypto.cryptos,timestamp:new Date().toISOString(),sources:{fiat:fiat.source,crypto:crypto.source},mock:fiat.mock||crypto.mock};try{await EphyraDB.put('market_cache',payload)}catch{}return payload}
async function getCache(){try{const cached=await EphyraDB.get('market_cache','market_cache');if(cached)return cached}catch{}return fetchAll('USD')}
function convert(amount,from,to,cache){const value=Number(amount);if(!Number.isFinite(value)||value<0)return null;const fiat=cache?.fiat||Object.fromEntries(Object.entries(FIAT_CATALOG).map(([code,meta])=>[code,meta[2]])),crypto=cache?.crypto||CRYPTO_MOCK,source=String(from||'').toUpperCase(),target=String(to||'').toUpperCase();let usd;if(Number.isFinite(fiat[source])&&fiat[source]>0)usd=value/fiat[source];else if(crypto[source]?.priceUSD>0)usd=value*crypto[source].priceUSD;else return null;if(Number.isFinite(fiat[target])&&fiat[target]>0)return usd*fiat[target];if(crypto[target]?.priceUSD>0)return usd/crypto[target].priceUSD;return null}
async function fetchHistory(assetId,assetType,period,localCurrency,cache){const days={"24h":1,"7d":7,"30d":30,"90d":90,"6m":180,"1y":365}[period]||30;if(assetType==='crypto'){const info=cache?.crypto?.[assetId];if(info?.id){try{const target=String(localCurrency||'usd').toLowerCase(),json=await fetchJSON(`https://api.coingecko.com/api/v3/coins/${info.id}/market_chart?vs_currency=${target}&days=${days}`,8000);if(Array.isArray(json.prices))return json.prices.map(([time,price])=>({x:time,y:price}))}catch{}}}const current=convert(1,assetId,localCurrency,cache)||1,source=assetType==='crypto'?cache?.crypto?.[assetId]?.sparkline:cache?.fiatSparklines?.[assetId],points=Array.isArray(source)&&source.length?source:makeSparkline(current,0,Math.min(days*4,120)),ratio=current/(points[points.length-1]||current);return points.map((price,index)=>({x:Date.now()-(points.length-index)*3600000,y:price*ratio}))}
function fiatAssets(cache){const rates=cache?.fiat||{},codes=new Set([...Object.keys(FIAT_CATALOG),...Object.keys(rates)]);return[...codes].filter(code=>ALL_FIAT_CODES.includes(code)).map(code=>{const meta=fiatMeta(code),rate=Number(rates[code])||FIAT_CATALOG[code]?.[2];return{code,name:meta.name,flag:meta.flag,rate,change:cache?.fiatChanges?.[code]||0,sparkline:cache?.fiatSparklines?.[code]||makeSparkline(rate||1,0,20)}}).filter(item=>Number.isFinite(item.rate)&&item.rate>0)}
function cryptoAssets(cache){const merged={...CRYPTO_MOCK,...(cache?.crypto||{})};return Object.entries(merged).map(([ticker,info])=>({ticker,...info})).filter(item=>Number.isFinite(item.priceUSD)&&item.priceUSD>0).sort((a,b)=>(b.marketCap||0)-(a.marketCap||0))}
return{fetchFiat,fetchCrypto,fetchAll,getCache,convert,fetchHistory,fiatAssets,cryptoAssets,makeSparkline,fiatMeta,FIAT_MOCK:FIAT_MOCK_BASE,FIAT_CATALOG,CRYPTO_MOCK,REQUIRED_CRYPTO};
})();
if(typeof window!=='undefined')window.MarketAPI=MarketAPI;