/** Ephyra Finance - central mundial de moedas e criptomoedas. */
const Market=(()=>{
'use strict';
let cache=null,localCurrency='BRL',favorites=[],alerts=[],query='',activeTab='moedas',detail=null,period='30d',historyChart=null,fiatTimer=0,cryptoTimer=0,searchTimer=0,historyToken=0;
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const escapeHTML=value=>String(value||'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
const favoriteKey=()=>`ephyra_market_favorites_${String(window.App?.user?.email||'guest').replace(/[^a-z0-9]/gi,'_')}`;
function detectLocalCurrency(){try{const language=navigator.language||'en-US',region=new Intl.Locale(language).region||'US',map={BR:'BRL',US:'USD',GB:'GBP',JP:'JPY',CH:'CHF',CA:'CAD',AU:'AUD',CN:'CNY',KR:'KRW',AR:'ARS',DE:'EUR',FR:'EUR',IT:'EUR',ES:'EUR',PT:'EUR',MX:'MXN',CL:'CLP',CO:'COP',PE:'PEN',UY:'UYU',PY:'PYG',IN:'INR',SG:'SGD',ZA:'ZAR',TR:'TRY',AE:'AED',SA:'SAR'};return map[region]||(language.startsWith('pt')?'BRL':'USD')}catch{return'BRL'}}
function loadLocalFavorites(){try{const value=JSON.parse(localStorage.getItem(favoriteKey())||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function persistLocalFavorites(){try{localStorage.setItem(favoriteKey(),JSON.stringify(favorites))}catch{}}
function ensureMarket(data){if(!data.market)data.market={favorites:[],alerts:[],defaultCurrency:data.config?.moeda||detectLocalCurrency()};if(!Array.isArray(data.market.favorites))data.market.favorites=[];if(!Array.isArray(data.market.alerts))data.market.alerts=[]}
async function init(data){ensureMarket(data);localCurrency=data.market.defaultCurrency||data.config?.moeda||detectLocalCurrency();const merged=new Map();[...data.market.favorites,...loadLocalFavorites()].forEach(item=>{if(item?.assetId)merged.set(item.assetId,item)});favorites=[...merged.values()];data.market.favorites=favorites;alerts=data.market.alerts;cache=await MarketAPI.getCache();cache.defaultCurrency=localCurrency;startTimers();MarketAPI.fetchAll('USD').then(payload=>{cache={...payload,defaultCurrency:localCurrency};renderIfVisible();checkAlerts()}).catch(()=>{});persist();}
function startTimers(){clearInterval(fiatTimer);clearInterval(cryptoTimer);fiatTimer=setInterval(refreshFiat,300000);cryptoTimer=setInterval(refreshCrypto,60000)}
async function refreshFiat(){try{const result=await MarketAPI.fetchFiat('USD');cache={...cache,fiat:result.rates,fiatChanges:result.changes,fiatSparklines:result.sparklines,timestamp:result.timestamp,mock:Boolean(result.mock||cache?.mock)};await EphyraDB.put('market_cache',{key:'market_cache',...cache});renderIfVisible();checkAlerts()}catch{}}
async function refreshCrypto(){try{const result=await MarketAPI.fetchCrypto();cache={...cache,crypto:result.cryptos,timestamp:result.timestamp,mock:Boolean(result.mock||cache?.mock)};await EphyraDB.put('market_cache',{key:'market_cache',...cache});renderIfVisible();checkAlerts()}catch{}}
function renderIfVisible(){if(window.App?.cp==='mercado')render()}
function fiatAssets(){return MarketAPI.fiatAssets(cache)}
function cryptoAssets(){return MarketAPI.cryptoAssets(cache)}
function matches(asset){if(!query)return true;const terms=normalize(`${asset.code||asset.ticker} ${asset.name}`);return terms.includes(query)}
function favoriteSort(a,b){const aId=a.code||a.ticker,bId=b.code||b.ticker,aFav=favorites.some(item=>item.assetId===aId),bFav=favorites.some(item=>item.assetId===bId);if(aFav!==bFav)return aFav?-1:1;return(a.name||aId).localeCompare(b.name||bId,'pt-BR')}
function render(){const container=document.getElementById('pg-mercado');if(!container)return;if(!cache){container.innerHTML='<div class="es"><div class="ei">💱</div><h3>Carregando mercado</h3><p>Buscando as cotações mais recentes.</p></div>';return}const simulated=Boolean(cache.mock),offline=!navigator.onLine;const statusLabel=simulated?'Dados simulados — não usar como cotação real':offline?'Offline · dados salvos':'Última atualização';container.innerHTML=`<div class="ph"><div><h2 class="pt">Mercado</h2><p class="psub">Central mundial de moedas e criptomoedas — base ${localCurrency}</p></div><div class="flx gs"><span class="badge ${simulated||offline?'bdd':'bdp'}"><i class="fas fa-${simulated?'triangle-exclamation':offline?'wifi':'clock'}"></i> ${statusLabel} ${new Date(cache.timestamp||Date.now()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><button class="btn btn-ghost btn-sm" onclick="Market.refresh()" aria-label="Atualizar cotações"><i class="fas fa-sync-alt"></i></button></div></div><div class="market-search"><i class="fas fa-search"></i><input id="market-search-input" value="${escapeHTML(query)}" placeholder="Pesquisar BTC, Bitcoin, USD, Dólar, Ethereum..." oninput="Market.search(this.value)" aria-label="Pesquisar ativos"></div><div id="market-trends"></div><div class="market-tabs"><button class="market-tab ${activeTab==='moedas'?'active':''}" data-tab="moedas" onclick="Market.switchTab('moedas')">Moedas</button><button class="market-tab ${activeTab==='cripto'?'active':''}" data-tab="cripto" onclick="Market.switchTab('cripto')">Criptomoedas</button><button class="market-tab ${activeTab==='conversor'?'active':''}" data-tab="conversor" onclick="Market.switchTab('conversor')">Conversor</button><button class="market-tab ${activeTab==='favoritos'?'active':''}" data-tab="favoritos" onclick="Market.switchTab('favoritos')">⭐ Favoritos</button></div><div id="market-tab-content"></div>`;renderTrends();renderCurrentTab()}
function renderTrends(){const container=document.getElementById('market-trends');if(!container)return;const all=[...fiatAssets().map(item=>({...item,assetType:'fiat'})),...cryptoAssets().map(item=>({...item,assetType:'crypto'}))].filter(item=>Number.isFinite(Number(item.change)));const gains=[...all].sort((a,b)=>b.change-a.change).slice(0,10),drops=[...all].sort((a,b)=>a.change-b.change).slice(0,10);container.innerHTML=`<div class="market-trends">${MarketUI.trendPanel('Mais valorizadas hoje','Top 10 maiores altas',gains,localCurrency,cache,true)}${MarketUI.trendPanel('Maiores quedas','Top 10 maiores baixas',drops,localCurrency,cache,false)}</div>`}
function renderCurrentTab(){const container=document.getElementById('market-tab-content');if(!container)return;if(query){renderSearchResults(container);return}if(activeTab==='moedas')renderFiat(container);else if(activeTab==='cripto')renderCrypto(container);else if(activeTab==='conversor')renderConverter(container);else renderFavorites(container)}
function renderSearchResults(container){const fiat=fiatAssets().filter(matches).sort(favoriteSort),crypto=cryptoAssets().filter(matches).sort((a,b)=>{const aFav=favorites.some(item=>item.assetId===a.ticker),bFav=favorites.some(item=>item.assetId===b.ticker);if(aFav!==bFav)return aFav?-1:1;return(b.marketCap||0)-(a.marketCap||0)});container.innerHTML=`<div class="market-results-info">${fiat.length+crypto.length} resultados para “${escapeHTML(query)}” em moedas e criptomoedas</div>${fiat.length?`<div class="market-section-heading"><div><h3>Moedas</h3><p>${fiat.length} resultados</p></div></div><div class="ga" style="margin-bottom:1.5rem">${fiat.map(item=>MarketUI.cardCurrency(item,localCurrency,favorites,cache)).join('')}</div>`:''}${crypto.length?`<div class="market-section-heading"><div><h3>Criptomoedas</h3><p>${crypto.length} resultados</p></div></div><div class="ga">${crypto.map(item=>MarketUI.cardCrypto(item,localCurrency,favorites,cache)).join('')}</div>`:''}${!fiat.length&&!crypto.length?emptySearch():''}`}
function renderFiat(container){const list=fiatAssets().filter(matches).sort(favoriteSort);container.innerHTML=`<div class="market-results-info">${list.length} moedas encontradas · favoritas aparecem primeiro</div>${list.length?`<div class="ga">${list.map(item=>MarketUI.cardCurrency(item,localCurrency,favorites,cache)).join('')}</div>`:emptySearch()}`}
function renderCrypto(container){const list=cryptoAssets().filter(matches).sort((a,b)=>{const aFav=favorites.some(item=>item.assetId===a.ticker),bFav=favorites.some(item=>item.assetId===b.ticker);if(aFav!==bFav)return aFav?-1:1;return(b.marketCap||0)-(a.marketCap||0)});container.innerHTML=`<div class="market-results-info">${list.length} criptomoedas encontradas · ordenadas por capitalização</div>${list.length?`<div class="ga">${list.map(item=>MarketUI.cardCrypto(item,localCurrency,favorites,cache)).join('')}</div>`:emptySearch()}`}
function renderConverter(container){container.innerHTML=MarketUI.converterTab(cache,localCurrency);const from=document.getElementById('conv-from'),to=document.getElementById('conv-to');if(from&&to){from.value='USD';to.value=localCurrency;convertLive()}}
function renderFavorites(container){container.innerHTML=MarketUI.favoritesTab(fiatAssets().sort(favoriteSort),cryptoAssets().sort(favoriteSort),favorites,localCurrency,cache)}
function emptySearch(){return'<div class="es"><div class="ei">🔎</div><h3>Nenhum ativo encontrado</h3><p>Tente pesquisar pelo nome, símbolo ou código.</p></div>'}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.market-tab').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));renderCurrentTab()}
function search(value){query=normalize(value);clearTimeout(searchTimer);searchTimer=setTimeout(renderCurrentTab,120)}
function finiteConversion(amount,from,to){const result=MarketAPI.convert(amount,from,to,cache);return Number.isFinite(result)?result:null}
function convertLive(){const from=document.getElementById('conv-from')?.value,to=document.getElementById('conv-to')?.value,source=document.getElementById('conv-from-amount'),target=document.getElementById('conv-to-amount'),info=document.getElementById('conv-rate-info'),result=document.getElementById('conv-result');if(!from||!to||!source)return;const amount=Number(source.value);if(!Number.isFinite(amount)||amount<0){if(target)target.value='';if(info)info.textContent='Informe um valor válido';if(result)result.textContent='';return}const converted=finiteConversion(amount,from,to),unit=finiteConversion(1,from,to);if(converted===null){if(target)target.value='';if(info)info.textContent='Cotação indisponível';if(result)result.textContent='Não foi possível converter';return}if(target)target.value=formatInput(converted);if(info)info.textContent=`1 ${from} = ${formatRate(unit)} ${to}`;if(result)result.textContent=`${amount.toLocaleString('pt-BR')} ${from} = ${formatRate(converted)} ${to}`}
function convertReverse(){const from=document.getElementById('conv-from'),to=document.getElementById('conv-to'),source=document.getElementById('conv-from-amount'),target=document.getElementById('conv-to-amount');if(!from||!to||!source||!target)return;const amount=Number(target.value);if(!Number.isFinite(amount)||amount<0){source.value='';return}const converted=finiteConversion(amount,to.value,from.value);source.value=converted===null?'':formatInput(converted);convertLive()}
function formatInput(value){return value<.0001?value.toFixed(8):value<1?value.toFixed(6):value.toFixed(2)}
function formatRate(value){return Number.isFinite(value)?value.toLocaleString('pt-BR',{maximumFractionDigits:value<1?8:4}):'—'}
function swapConverter(){const from=document.getElementById('conv-from'),to=document.getElementById('conv-to'),source=document.getElementById('conv-from-amount'),target=document.getElementById('conv-to-amount');if(!from||!to)return;[from.value,to.value]=[to.value,from.value];if(source&&target)[source.value,target.value]=[target.value||source.value,source.value];convertLive()}
async function toggleFav(assetId,assetType){if(!window.App?.data)return;const exists=favorites.some(item=>item.assetId===assetId);favorites=exists?favorites.filter(item=>item.assetId!==assetId):[...favorites,{assetId,assetType,addedAt:new Date().toISOString()}];App.data.market.favorites=favorites;persistLocalFavorites();await persist();renderCurrentTab();Toast?.s(exists?'Removido dos favoritos':`⭐ ${assetId} favoritado!`)}
async function persist(){if(App.user?.email)await EphyraStorage.saveUserData(App.user.email,App.data)}
function showDetail(assetId,assetType){detail={assetId,assetType};period='30d';const info=assetType==='fiat'?fiatAssets().find(item=>item.code===assetId):cryptoAssets().find(item=>item.ticker===assetId),container=document.getElementById('pg-mercado');if(!info||!container)return;container.innerHTML=`<div class="ph"><div><button class="btn btn-ghost btn-sm" onclick="Market.backToMarket()"><i class="fas fa-arrow-left"></i> Voltar ao Mercado</button><h2 class="pt" style="margin-top:.6rem">${escapeHTML(info.name)} — ${assetId}</h2><p class="psub">Detalhes, histórico e conversão rápida</p></div></div><section class="market-detail-page">${MarketUI.detailModal(assetId,assetType,info,localCurrency,cache)}</section>`;window.scrollTo({top:0,behavior:'smooth'});quickConvert(assetId);renderAlertsList();renderHistoryChart()}
function backToMarket(){detail=null;if(historyChart){historyChart.destroy();historyChart=null}render()}
async function setPeriod(value){period=value;await renderHistoryChart()}
async function renderHistoryChart(){if(!detail)return;const token=++historyToken,canvas=document.getElementById('market-history-chart');if(!canvas)return;const points=await MarketAPI.fetchHistory(detail.assetId,detail.assetType,period,localCurrency,cache);if(token!==historyToken||!document.getElementById('market-history-chart'))return;if(historyChart)historyChart.destroy();historyChart=new Chart(canvas,{type:'line',data:{labels:points.map(point=>new Date(point.x).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})),datasets:[{label:detail.assetId,data:points.map(point=>point.y),borderColor:'#7c3aed',backgroundColor:'rgba(124,58,237,.1)',fill:true,tension:.35,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#64748b',maxTicksLimit:6}},y:{grid:{color:'rgba(148,163,184,.12)'},ticks:{color:'#64748b',callback:value=>MarketUI.fmtMoney(value,localCurrency)}}}}})}
function quickConvert(assetId){const amount=Number(document.getElementById('detail-quick-amount')?.value),output=document.getElementById('detail-quick-result');if(!output)return;const result=finiteConversion(amount,assetId,localCurrency);output.value=result===null?'Cotação indisponível':MarketUI.fmtMoney(result,localCurrency)}
async function createAlert(assetId,assetType){const condition=document.getElementById('alert-cond')?.value||'>',value=Number(document.getElementById('alert-value')?.value);if(!Number.isFinite(value)||value<=0){Toast?.e('Informe um valor válido');return}const alert={id:`al_${Date.now()}`,assetId,assetType,condition,value,currency:localCurrency,active:true,createdAt:new Date().toISOString()};alerts.push(alert);App.data.market.alerts=alerts;await persist();Toast?.s(`Alerta criado para ${assetId}`);renderAlertsList()}
function renderAlertsList(){const container=document.getElementById('alerts-list');if(!container)return;const relevant=alerts.filter(item=>item.assetId===detail?.assetId);container.innerHTML=relevant.length?relevant.map(item=>`<div class="card" style="padding:.75rem 1rem;display:flex;justify-content:space-between;align-items:center;margin-bottom:.5rem"><span class="txm"><strong>${item.assetId}</strong> ${item.condition} ${item.value.toLocaleString('pt-BR')} ${item.currency}</span><button class="btn btn-ghost btn-sm" onclick="Market.removeAlert('${item.id}')"><i class="fas fa-trash"></i></button></div>`).join(''):'<p class="txs tm">Nenhum alerta para este ativo.</p>'}
async function removeAlert(id){alerts=alerts.filter(item=>item.id!==id);App.data.market.alerts=alerts;await persist();renderAlertsList();Toast?.s('Alerta removido')}
function checkAlerts(){const triggered=MarketAlerts.check(alerts,cache,localCurrency);triggered.forEach(({alert,current})=>{Toast?.s(`🔔 ${alert.assetId}: ${current.toFixed(2)} ${alert.currency}`);alert.active=false});App.data.market.alerts=alerts;if(triggered.length)persist()}
async function refresh(){try{cache={...(await MarketAPI.fetchAll('USD')),defaultCurrency:localCurrency};render();checkAlerts();if(cache.mock)Toast?.w('Fontes indisponíveis: exibindo dados simulados');else Toast?.s('Cotações atualizadas')}catch{Toast?.e('Falha ao atualizar cotações')}}
function setDefaultCurrency(currency){localCurrency=currency;if(window.App?.data){App.data.market.defaultCurrency=currency;App.data.config.moeda=currency;App.saveData()}if(cache)cache.defaultCurrency=currency;renderIfVisible()}
function renderIfVisible(){if(window.App?.cp==='mercado')render()}
function destroy(){clearInterval(fiatTimer);clearInterval(cryptoTimer);clearTimeout(searchTimer);if(historyChart)historyChart.destroy();historyChart=null}
return{init,render,switchTab,search,convertLive,convertReverse,swapConverter,toggleFav,showDetail,backToMarket,setPeriod,quickConvert,createAlert,removeAlert,refresh,setDefaultCurrency,detectLocalCurrency,checkAlerts,destroy,get cache(){return cache},get favorites(){return favorites},get localCurrency(){return localCurrency}};
})();
if(typeof window!=='undefined')window.Market=Market;
